[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools >= 61.0", "wheel"]

[project]
name = "svgtag"
requires-python = ">=3.8"
version = "0.8.1"
authors = [{name = "Stéphane Besnard", email = "stephane.c.m.besnard@gmail.com"}]
description = "Process SVG files for generation of laser or 3D files."
keywords = ["graphics", "laser", "mesh", "3D"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Natural Language :: English",
    "Topic :: Scientific/Engineering",
    "Topic :: Multimedia :: Graphics",
    "Topic :: Multimedia :: Graphics :: 3D Modeling"
]
dependencies = [
    "fonttools>=4.48.1",
    "shapely>=2.0",
]

[project.urls]
homepage = "https://github.com/PetitPhoenix/svgtag"
documentation = "https://github.com/PetitPhoenix/svgtag"

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.optional-dependencies]
3D = [
    "trimesh[easy]>=4.10",
    "qrcode",
]

developer = [
    "Pillow",
    "matplotlib",
    "pandas",
    "numpy",
]

all = [
    "trimesh>=4.10",
    "qrcode",
    "Pillow",
    "matplotlib",
    "pandas",
    "numpy",
]

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
target-version = "py38"
line-length = 90

[tool.ruff.lint]
select = [
    "B",
    "C",
    "E",
    "F",
    "I",
    "RUF",
    "UP",
    "W",
    "YTT",
    "ISC001",
    "ISC002",
    "NPY201",
    "TID251"
]

ignore = [
  "C901",
  "N802",
  "N806",
  "E501",
  "B904",
  "B905",
  "RUF005",
]

flake8-implicit-str-concat = {"allow-multiline" = false}

[tool.ruff.lint.flake8-tidy-imports.banned-api]
"IPython.embed".msg = "you forgot to remove a debug embed ;)"
"numpy.empty".msg = "uninitialized arrays are haunted try numpy.zeros"

[tool.codespell]
skip = "*.js*,./docs/built/*,./docs/generate/*,./models*,*.toml"
ignore-words-list = "nd,coo,whats,bu,childs,mis,filetests"

[tool.mypy]
python_version = "3.8"
ignore_missing_imports = true
disallow_untyped_defs = false
disallow_untyped_calls = false
disable_error_code = ["method-assign", "var-annotated"]